version: "3.8"
services:
  database:
    image: mongo
    container_name: wetywebsite_database
  env:
    - MONGO_USERNAME=root
    - MONGO_PASSWORD=root
  api:
    dependOn:
      - database
    build:
      image: wetywebsite_api
      container_name: wetywebsite_api
      context: .
      dockerfile: Dockerfile
    ports:
      - 2023:43000
    volumes:
      - src:/app/src
      - package.json:/app/package.json
      - package-lock.json:/app/package-lock.json
    env_file:
      - .env.docker
networks:
  wetywebsiteapi:
volumes:
  wetywebsiteapi:
